heap output for MNPR, MScalar, and MScalarSUN
RChrHill/Hadrons pull request #2
Opened 2023-03-08 15:08 UTC by krox

here are the changes as discussed. AFAIK thats all done.

2023-03-08 15:24 UTC, krox commented
uh, wait. this is wrong. only meant to PR my changes

2023-03-17 14:59 UTC, RChrHill requested changes
Looks good overall, just a few minor stylistic points to revert in order to keep overall consistency within Hadrons.

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalar/ChargedProp.cpp
> +    return {par().source, par().emField};
We should keep `void` in the argument signature and keep `in` as a separate `std::vector<std::string>` for consistency with the rest of Hadrons here.

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalar/ChargedProp.cpp
> +    return {getName(), getName()+"_0", getName()+"_Q", getName()+"_Sun", getName()+"_Tad", getName()+"_projections"};
We should keep `void` in the argument signature and keep `out` as a separate `std::vector<std::string>` for consistency with the rest of Hadrons here.

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalar/ChargedProp.cpp
> +void TChargedProp::setup()
Keep void in argument sig for consistency with the rest of Hadrons

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalar/ChargedProp.cpp
> +void TChargedProp::execute()
Keep void in argument sig for consistency with the rest of Hadrons

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalar/FreeProp.cpp
> +    return {par().source};
We should keep `void` in the argument signature and keep `in` as a separate `std::vector<std::string>` for consistency with the rest of Hadrons here.

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalar/FreeProp.cpp
> +    return {getName(), getName()+"_sliceSum"};
We should keep `void` in the argument signature and keep `out` as a separate `std::vector<std::string>` for consistency with the rest of Hadrons here.

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalar/FreeProp.cpp
> +void TFreeProp::setup()
Keep void in the argument sig for consistency with Hadrons

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalar/FreeProp.cpp
> +void TFreeProp::execute()
Keep void in the argument sig for consistency with the rest of Hadrons

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalarSUN/Div.hpp
> +std::vector<std::string> TDiv<SImpl>::getInput()
Keep void in the argument sig for consistency with the rest of Hadrons

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalarSUN/Div.hpp
>  }
We should keep `void` in the argument signature and keep `out` as a separate `std::vector<std::string>` for consistency with the rest of Hadrons here.

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalarSUN/Div.hpp
> +void TDiv<SImpl>::setup()
Keep void in the argument sig for consistency with the rest of Hadrons

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalarSUN/TwoPoint.hpp
> +    return {getName()};
We should keep `out` as a separate `std::vector<std::string>` for consistency with the rest of Hadrons here.

2023-03-17 14:59 UTC, RChrHill commented on Hadrons/Modules/MScalarSUN/TwoPointNPR.hpp
> +    return {getName()};
We should keep `out` as a separate `std::vector<std::string>` for consistency with the rest of Hadrons here.

2023-03-21 11:06 UTC, krox commented
I re-added the `(void)` parameters. These have exactly no effect in (any version of) C++, so you might be right for stylistic consistency. But I cant bring myself to write `std::vector<std::string> in = ...; return in` . That just looks silly to me to needlessly repeat the type name. And in some (older) versions of C++ it can even be less efficient. (Definitely not relevant here of course. Just a matter of principle).

I know I am a bit of a style snob here, I am sorry. This discussion is not really worth my or your time. I will not object to any changes you feel like making. Thanks for your work.

2023-03-21 11:10 UTC, RChrHill commented
I'll merge the PR and clear up any requests for further style changes from higher up myself. Thanks for your work!

2023-03-21 11:11 UTC, merged